version: '3.8'

services:
  api:
    image: spring-boot/ws-bank-transaction
    ports:
      - "8081:8080"
#    volumes:
#      - ./target/ws-bank-transaction-0.0.1-SNAPSHOT.jar:/app/ws-bank-transaction.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_transaction_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: bank_transaction_db
#    volumes:
#      - db_data:/var/lib/postgresql/data